CREATE TABLE users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL 
);

CREATE TABLE user_sessions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    refresh_token VARCHAR(100) NOT NULL,
    expiration_time_utc TIMESTAMP NOT NULL,

    CONSTRAINT fk_user_sessions_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE 
);